name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Google Key
        run: |
          echo "Google Key is $GOOGLE_KEY"
        env:
          GOOGLE_KEY: ${{ secrets.googlekey }}
